### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by OoDeLally** [razum2um/google-translate-anki#1]
Hello,
I freshly installed the extension.
It seems to behave exactly like Google Translate. I get the translation popup. But I don't see any sign of it adding the card. Am I supposed to click on a button or something?
The extension seems correctly configured and my desktop anki is running with the server addon (another Chrome extension can successfully connect to it).
I've waited at least 20sec with the popup open, so I dont think it is a matter of time.
How can I figure out wether the extension does anything whatsoever?
Thank you

**Comment by razum2um** [comment]
See usage in README, please - click on translation and wait.
If you can - open chrome devtools and see network panel for a xhr request to ankiconnect server

**Comment by OoDeLally** [comment]
Hello,
There is no XHR request done, and the console doesn't log any error.
I made a little video showing it:
https://youtu.be/vuuddoJ-J9Y
Thank you

**Comment by razum2um** [comment]
Thanks for video, as I can see - you didn't even hover upon translation. You must click on translated english sentence inside the popup to make request. I wrote this above and in readme :)

p.s. I didn't want to auto-add everything I translate

**Comment by OoDeLally** [comment]
Ok now I understand. It was not clear to me where to click, especially when I'm translating a whole sentence, the "translated word" doesn't make sense. I thought what you call "translation" was the whole popup.
It works fine now! :-)
I would suggest to make it clear in your README that it is the click that triggers it. Make a circle around the translated word on your screenshot, or append an explicit "Add to Anki" button. Currently there is nothing showing that the translated sentence is clickable :-)
