### ISSUE TITLE
Firefox extension please

### ISSUE THREAD

**Issue by omega3** [razum2um/google-translate-anki#2]
Can you please create this extension for Firefox?

**Comment by razum2um** [comment]
I just modified original google's code. Unfortunately, I think they didn't package the same code for firefox: there're a lot of `chrome.` calls across the source code, which makes it hard to do this universal.

So I think the best strategy is just making same thing as I did to any/best plugin in ff land: totally separeted.
As I'm not actively using firefox - I don't think this will happen any time soon from my side.
